version: '3.8'

services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_recettes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    image: backend:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: app_recettes
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    ports:
      - "8081:8081" 
    depends_on:
      - db

  frontend:
    image: frontend:latest
    ports:
      - "3000:3000" 
    depends_on:
      - backend
