name: Test de build et de démarrage

on:
  pull_request:
    branches:
      - production
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installation des dépendances
      run: npm install

    - name: Test de build
      run: npm run build

    - name: Test de démarrage
      run: npm start
